# Generated by Django 2.1 on 2018-12-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_page_category_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('story_base_image', models.CharField(max_length=400)),
                ('story_heading', models.TextField(default=None, max_length=500)),
                ('story_writter_name', models.CharField(max_length=100)),
                ('story_publish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='index_page_repeat_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_base_image', models.CharField(max_length=400)),
                ('story_heading', models.TextField(default=None, max_length=500)),
                ('story_writter_name', models.CharField(max_length=100)),
                ('story_publish_date', models.DateTimeField()),
            ],
        ),
    ]
