# Generated by Django 2.1 on 2018-12-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_page_category_data',
            name='story_base_image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='index_page_repeat_data',
            name='story_base_image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
