# Generated by Django 2.1 on 2018-12-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181206_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='story_page_view',
            fields=[
                ('story_id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('story_base_image', models.CharField(max_length=400)),
                ('story_base_image_name', models.CharField(blank=True, max_length=50, null=True)),
                ('story_heading', models.TextField(default=None, max_length=500)),
                ('story_writter_name', models.CharField(max_length=100)),
                ('story_publish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='story_page_view_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_story_img_seq', models.IntegerField(default=1, max_length=2, unique=True)),
                ('desc_story_img', models.CharField(max_length=200)),
                ('desc_story_img_name', models.CharField(max_length=50)),
                ('desc_story_img_title', models.CharField(max_length=100)),
                ('desc_story_img_content', models.TextField(max_length=1500)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.story_page_view')),
            ],
        ),
    ]
