# Generated by Django 2.1 on 2018-12-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_story_page_view_story_page_view_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_page_view',
            name='story_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
