# Generated by Django 2.1 on 2018-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181207_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_page_view_blog',
            name='desc_story_img_seq',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
