# Generated by Django 2.1 on 2019-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181207_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_page_recent_stories_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('story_base_image_name', models.CharField(blank=True, max_length=50, null=True)),
                ('story_base_image', models.CharField(max_length=400)),
                ('story_heading', models.TextField(default=None, max_length=500)),
                ('story_writter_name', models.CharField(max_length=100)),
                ('story_publish_date', models.DateTimeField()),
            ],
        ),
    ]
