# Generated by Django 2.1 on 2019-05-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_index_page_recent_stories_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_page_view_blog',
            name='story_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.index_page_category_data'),
        ),
    ]
