# Generated by Django 2.1 on 2018-08-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='web_pages',
            new_name='web_page',
        ),
    ]
