# Generated by Django 2.1 on 2018-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0002_auto_20180813_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_page',
            name='sep',
            field=models.CharField(default='|', max_length=4),
            preserve_default=False,
        ),
    ]
