# Generated by Django 2.1 on 2018-08-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0003_web_page_sep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_page',
            name='sep',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
