# Generated by Django 2.1 on 2018-08-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0004_auto_20180814_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='web_page',
            new_name='nav_header',
        ),
    ]
