# Generated by Django 2.1 on 2018-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0005_auto_20180815_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50)),
                ('about_img_src', models.CharField(max_length=100)),
                ('about_short_desc', models.CharField(max_length=300)),
            ],
        ),
    ]
