# Generated by Django 2.1 on 2018-08-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0008_auto_20180827_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_latest_story',
            name='one_liner_title',
        ),
        migrations.AddField(
            model_name='homepage_latest_story',
            name='one_liner_recipie_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
