# Generated by Django 2.1 on 2018-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0011_auto_20180827_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_header',
            name='head_menu_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
