# Generated by Django 2.1 on 2018-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0012_nav_header_head_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_story',
            fields=[
                ('story_number', models.AutoField(primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=100)),
                ('story_one_liner', models.CharField(max_length=250)),
            ],
        ),
    ]
