# Generated by Django 2.1 on 2018-09-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0013_create_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_story',
            new_name='CreateStory',
        ),
    ]
