# Generated by Django 2.1 on 2018-09-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0014_auto_20180913_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateStory',
        ),
    ]
