# Generated by Django 2.1 on 2018-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0015_delete_createstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStory',
            fields=[
                ('story_number', models.AutoField(primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=100)),
                ('story_one_liner', models.CharField(max_length=250)),
            ],
        ),
    ]
