# Generated by Django 2.1 on 2018-09-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0016_createstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStory_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('BLANK', 'BLANK'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='BLANK', max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
                ('video_heading', models.FileField(max_length=200, upload_to='')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='')),
                ('image_heading', models.FileField(max_length=200, upload_to='')),
                ('text_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('text_desc_heading', models.CharField(max_length=200)),
                ('media_position', models.IntegerField()),
                ('story_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostacor.CreateStory')),
            ],
        ),
    ]
