# Generated by Django 2.1 on 2018-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0017_createstory_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstory_media',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='story_image'),
        ),
    ]
