# Generated by Django 2.1 on 2018-09-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0019_auto_20180913_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createstory_media',
            name='media_type',
        ),
    ]
