# Generated by Django 2.1 on 2018-09-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostacor', '0022_auto_20180913_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstory_media',
            name='image_file',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
