# Generated by Django 2.0.7 on 2018-09-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStoryHeader',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('one_liner', models.CharField(max_length=150)),
            ],
        ),
    ]
