# Generated by Django 2.0.7 on 2018-09-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createstoryheader',
            name='story_id',
        ),
        migrations.AddField(
            model_name='createstoryheader',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
